// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmUDW6GXT4NfQYA4TMpT23hMPquY74Q38',
    appId: '1:643587438820:web:8b58619071dab69b0e54f1',
    messagingSenderId: '643587438820',
    projectId: 'sokolovchat',
    authDomain: 'sokolovchat.firebaseapp.com',
    storageBucket: 'sokolovchat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bVUypPq7WUnGv-ssS06D-jpDczBplFM',
    appId: '1:643587438820:android:734dc6401a900d780e54f1',
    messagingSenderId: '643587438820',
    projectId: 'sokolovchat',
    storageBucket: 'sokolovchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoOmcq_uZhd6QFpGeAmd_WeF2dYIcy24',
    appId: '1:643587438820:ios:10f28af11b2772350e54f1',
    messagingSenderId: '643587438820',
    projectId: 'sokolovchat',
    storageBucket: 'sokolovchat.firebasestorage.app',
    iosBundleId: 'com.example.sokolovChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUoOmcq_uZhd6QFpGeAmd_WeF2dYIcy24',
    appId: '1:643587438820:ios:10f28af11b2772350e54f1',
    messagingSenderId: '643587438820',
    projectId: 'sokolovchat',
    storageBucket: 'sokolovchat.firebasestorage.app',
    iosBundleId: 'com.example.sokolovChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmUDW6GXT4NfQYA4TMpT23hMPquY74Q38',
    appId: '1:643587438820:web:c12b15bea5cc49480e54f1',
    messagingSenderId: '643587438820',
    projectId: 'sokolovchat',
    authDomain: 'sokolovchat.firebaseapp.com',
    storageBucket: 'sokolovchat.firebasestorage.app',
  );
}
